[theme]
primaryColor="#ce2430"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#94232b"
textColor="#262730"
font="sans serif"

#primaryColor="#00FF00"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#24c956"
#textColor="#262730"
#font="sans serif"
#gatherUsageStats = false
